/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alewis' at '5/26/16 10:31 AM' with Gradle 2.9
 *
 * @author alewis, @date 5/26/16 10:31 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
